/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminUsersRouteImport } from './routes/admin.admin-users'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminColorsRouteImport } from './routes/admin.colors'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProductionRouteImport } from './routes/admin.production'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSizesRouteImport } from './routes/admin.sizes'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVariantsRouteImport } from './routes/admin.variants'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as AdminCustomizationIndexRouteImport } from './routes/admin.customization.index'
import { Route as AdminCustomizationArtworksRouteImport } from './routes/admin.customization.artworks'
import { Route as AdminCustomizationOptionsRouteImport } from './routes/admin.customization.options'
import { Route as AdminCustomizationPrintingMethodsRouteImport } from './routes/admin.customization.printing-methods'
import { Route as AdminInventoryIndexRouteImport } from './routes/admin.inventory.index'
import { Route as AdminInventoryAdjustmentsRouteImport } from './routes/admin.inventory.adjustments'
import { Route as AdminInventoryLowStockRouteImport } from './routes/admin.inventory.low-stock'
import { Route as AdminInventoryMovementsRouteImport } from './routes/admin.inventory.movements'
import { Route as AdminInventoryPurchaseOrdersRouteImport } from './routes/admin.inventory.purchase-orders'
import { Route as AdminInventoryStockRouteImport } from './routes/admin.inventory.stock'
import { Route as AdminInventorySuppliersRouteImport } from './routes/admin.inventory.suppliers'
import { Route as AdminInventoryWarehousesRouteImport } from './routes/admin.inventory.warehouses'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminProductsCreateRouteImport } from './routes/admin.products.create'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin.shipments.index'
import { Route as AdminShipmentsIdRouteImport } from './routes/admin.shipments.$id'
import { Route as AdminSupportIndexRouteImport } from './routes/admin.support.index'
import { Route as AdminSupportIdRouteImport } from './routes/admin.support.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColorsRoute = AdminColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductionRoute = AdminProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSizesRoute = AdminSizesRouteImport.update({
  id: '/sizes',
  path: '/sizes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVariantsRoute = AdminVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomizationIndexRoute = AdminCustomizationIndexRouteImport.update({
  id: '/customization/',
  path: '/customization/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomizationArtworksRoute =
  AdminCustomizationArtworksRouteImport.update({
    id: '/customization/artworks',
    path: '/customization/artworks',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomizationOptionsRoute =
  AdminCustomizationOptionsRouteImport.update({
    id: '/customization/options',
    path: '/customization/options',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCustomizationPrintingMethodsRoute =
  AdminCustomizationPrintingMethodsRouteImport.update({
    id: '/customization/printing-methods',
    path: '/customization/printing-methods',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInventoryIndexRoute = AdminInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryAdjustmentsRoute =
  AdminInventoryAdjustmentsRouteImport.update({
    id: '/inventory/adjustments',
    path: '/inventory/adjustments',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInventoryLowStockRoute = AdminInventoryLowStockRouteImport.update({
  id: '/inventory/low-stock',
  path: '/inventory/low-stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryMovementsRoute = AdminInventoryMovementsRouteImport.update({
  id: '/inventory/movements',
  path: '/inventory/movements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryPurchaseOrdersRoute =
  AdminInventoryPurchaseOrdersRouteImport.update({
    id: '/inventory/purchase-orders',
    path: '/inventory/purchase-orders',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInventoryStockRoute = AdminInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventorySuppliersRoute = AdminInventorySuppliersRouteImport.update({
  id: '/inventory/suppliers',
  path: '/inventory/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryWarehousesRoute =
  AdminInventoryWarehousesRouteImport.update({
    id: '/inventory/warehouses',
    path: '/inventory/warehouses',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsIdRoute = AdminShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customization/artworks': typeof AdminCustomizationArtworksRoute
  '/admin/customization/options': typeof AdminCustomizationOptionsRoute
  '/admin/customization/printing-methods': typeof AdminCustomizationPrintingMethodsRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory/movements': typeof AdminInventoryMovementsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/suppliers': typeof AdminInventorySuppliersRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customization/': typeof AdminCustomizationIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customization/artworks': typeof AdminCustomizationArtworksRoute
  '/admin/customization/options': typeof AdminCustomizationOptionsRoute
  '/admin/customization/printing-methods': typeof AdminCustomizationPrintingMethodsRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory/movements': typeof AdminInventoryMovementsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/suppliers': typeof AdminInventorySuppliersRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/customization': typeof AdminCustomizationIndexRoute
  '/admin/inventory': typeof AdminInventoryIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/support': typeof SupportRoute
  '/wishlist': typeof WishlistRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/colors': typeof AdminColorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/production': typeof AdminProductionRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sizes': typeof AdminSizesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/customization/artworks': typeof AdminCustomizationArtworksRoute
  '/admin/customization/options': typeof AdminCustomizationOptionsRoute
  '/admin/customization/printing-methods': typeof AdminCustomizationPrintingMethodsRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/low-stock': typeof AdminInventoryLowStockRoute
  '/admin/inventory/movements': typeof AdminInventoryMovementsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/suppliers': typeof AdminInventorySuppliersRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/shipments/$id': typeof AdminShipmentsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/customization/': typeof AdminCustomizationIndexRoute
  '/admin/inventory/': typeof AdminInventoryIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/register'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/admin/admin-users'
    | '/admin/audit-logs'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/colors'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/materials'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/pricing'
    | '/admin/production'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/users'
    | '/admin/variants'
    | '/orders/$id'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/admin/customers/$id'
    | '/admin/customization/artworks'
    | '/admin/customization/options'
    | '/admin/customization/printing-methods'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/movements'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/suppliers'
    | '/admin/inventory/warehouses'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/create'
    | '/admin/shipments/$id'
    | '/admin/support/$id'
    | '/admin/customers/'
    | '/admin/customization/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/shipments/'
    | '/admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/register'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/admin/admin-users'
    | '/admin/audit-logs'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/colors'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/materials'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/pricing'
    | '/admin/production'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/users'
    | '/admin/variants'
    | '/orders/$id'
    | '/products/$slug'
    | '/admin'
    | '/products'
    | '/admin/customers/$id'
    | '/admin/customization/artworks'
    | '/admin/customization/options'
    | '/admin/customization/printing-methods'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/movements'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/suppliers'
    | '/admin/inventory/warehouses'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/create'
    | '/admin/shipments/$id'
    | '/admin/support/$id'
    | '/admin/customers'
    | '/admin/customization'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/shipments'
    | '/admin/support'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/notifications'
    | '/orders'
    | '/register'
    | '/studio'
    | '/support'
    | '/wishlist'
    | '/admin/admin-users'
    | '/admin/audit-logs'
    | '/admin/brands'
    | '/admin/catalog'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/colors'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/invoices'
    | '/admin/login'
    | '/admin/materials'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/pricing'
    | '/admin/production'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sizes'
    | '/admin/users'
    | '/admin/variants'
    | '/orders/$id'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
    | '/admin/customers/$id'
    | '/admin/customization/artworks'
    | '/admin/customization/options'
    | '/admin/customization/printing-methods'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/low-stock'
    | '/admin/inventory/movements'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/suppliers'
    | '/admin/inventory/warehouses'
    | '/admin/orders/$id'
    | '/admin/products/$id'
    | '/admin/products/create'
    | '/admin/shipments/$id'
    | '/admin/support/$id'
    | '/admin/customers/'
    | '/admin/customization/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/shipments/'
    | '/admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BulkOrdersRoute: typeof BulkOrdersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudioRoute: typeof StudioRoute
  SupportRoute: typeof SupportRoute
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-users': {
      id: '/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colors': {
      id: '/admin/colors'
      path: '/colors'
      fullPath: '/admin/colors'
      preLoaderRoute: typeof AdminColorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/production': {
      id: '/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AdminProductionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sizes': {
      id: '/admin/sizes'
      path: '/sizes'
      fullPath: '/admin/sizes'
      preLoaderRoute: typeof AdminSizesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/variants': {
      id: '/admin/variants'
      path: '/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AdminVariantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customization/': {
      id: '/admin/customization/'
      path: '/customization'
      fullPath: '/admin/customization/'
      preLoaderRoute: typeof AdminCustomizationIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customization/artworks': {
      id: '/admin/customization/artworks'
      path: '/customization/artworks'
      fullPath: '/admin/customization/artworks'
      preLoaderRoute: typeof AdminCustomizationArtworksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customization/options': {
      id: '/admin/customization/options'
      path: '/customization/options'
      fullPath: '/admin/customization/options'
      preLoaderRoute: typeof AdminCustomizationOptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customization/printing-methods': {
      id: '/admin/customization/printing-methods'
      path: '/customization/printing-methods'
      fullPath: '/admin/customization/printing-methods'
      preLoaderRoute: typeof AdminCustomizationPrintingMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/': {
      id: '/admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminInventoryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/adjustments': {
      id: '/admin/inventory/adjustments'
      path: '/inventory/adjustments'
      fullPath: '/admin/inventory/adjustments'
      preLoaderRoute: typeof AdminInventoryAdjustmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/low-stock': {
      id: '/admin/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/admin/inventory/low-stock'
      preLoaderRoute: typeof AdminInventoryLowStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/movements': {
      id: '/admin/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/admin/inventory/movements'
      preLoaderRoute: typeof AdminInventoryMovementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/purchase-orders': {
      id: '/admin/inventory/purchase-orders'
      path: '/inventory/purchase-orders'
      fullPath: '/admin/inventory/purchase-orders'
      preLoaderRoute: typeof AdminInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/stock': {
      id: '/admin/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/admin/inventory/stock'
      preLoaderRoute: typeof AdminInventoryStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/suppliers': {
      id: '/admin/inventory/suppliers'
      path: '/inventory/suppliers'
      fullPath: '/admin/inventory/suppliers'
      preLoaderRoute: typeof AdminInventorySuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory/warehouses': {
      id: '/admin/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/admin/inventory/warehouses'
      preLoaderRoute: typeof AdminInventoryWarehousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/shipments'
      fullPath: '/admin/shipments/'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments/$id': {
      id: '/admin/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/admin/shipments/$id'
      preLoaderRoute: typeof AdminShipmentsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/support/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminColorsRoute: typeof AdminColorsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProductionRoute: typeof AdminProductionRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSizesRoute: typeof AdminSizesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVariantsRoute: typeof AdminVariantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminCustomizationArtworksRoute: typeof AdminCustomizationArtworksRoute
  AdminCustomizationOptionsRoute: typeof AdminCustomizationOptionsRoute
  AdminCustomizationPrintingMethodsRoute: typeof AdminCustomizationPrintingMethodsRoute
  AdminInventoryAdjustmentsRoute: typeof AdminInventoryAdjustmentsRoute
  AdminInventoryLowStockRoute: typeof AdminInventoryLowStockRoute
  AdminInventoryMovementsRoute: typeof AdminInventoryMovementsRoute
  AdminInventoryPurchaseOrdersRoute: typeof AdminInventoryPurchaseOrdersRoute
  AdminInventoryStockRoute: typeof AdminInventoryStockRoute
  AdminInventorySuppliersRoute: typeof AdminInventorySuppliersRoute
  AdminInventoryWarehousesRoute: typeof AdminInventoryWarehousesRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminShipmentsIdRoute: typeof AdminShipmentsIdRoute
  AdminSupportIdRoute: typeof AdminSupportIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminCustomizationIndexRoute: typeof AdminCustomizationIndexRoute
  AdminInventoryIndexRoute: typeof AdminInventoryIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBrandsRoute: AdminBrandsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminColorsRoute: AdminColorsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProductionRoute: AdminProductionRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSizesRoute: AdminSizesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVariantsRoute: AdminVariantsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminCustomizationArtworksRoute: AdminCustomizationArtworksRoute,
  AdminCustomizationOptionsRoute: AdminCustomizationOptionsRoute,
  AdminCustomizationPrintingMethodsRoute:
    AdminCustomizationPrintingMethodsRoute,
  AdminInventoryAdjustmentsRoute: AdminInventoryAdjustmentsRoute,
  AdminInventoryLowStockRoute: AdminInventoryLowStockRoute,
  AdminInventoryMovementsRoute: AdminInventoryMovementsRoute,
  AdminInventoryPurchaseOrdersRoute: AdminInventoryPurchaseOrdersRoute,
  AdminInventoryStockRoute: AdminInventoryStockRoute,
  AdminInventorySuppliersRoute: AdminInventorySuppliersRoute,
  AdminInventoryWarehousesRoute: AdminInventoryWarehousesRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminShipmentsIdRoute: AdminShipmentsIdRoute,
  AdminSupportIdRoute: AdminSupportIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminCustomizationIndexRoute: AdminCustomizationIndexRoute,
  AdminInventoryIndexRoute: AdminInventoryIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BulkOrdersRoute: BulkOrdersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudioRoute: StudioRoute,
  SupportRoute: SupportRoute,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
